### ISSUE TITLE
uses Modelica 2.2.1?

### ISSUE THREAD

**Issue by dietmarw** [raulrpearson/PVSystems#1]
I guess that is a mistake right?

**Comment by raulrpearson** [comment]
I've been using Dymola 6.1 and that's the highest MSL version that comes with it. I'm working on moving to a more recent version of Dymola or might even consider switching to OpenModelica, but that's what I have now.

**Comment by dietmarw** [comment]
Ok I see. In that case the MSL version makes sense.
