### ISSUE TITLE
PVInverter1Phase increasing AC amplitude 

### ISSUE THREAD

**Issue by AggelikiGk** [raulrpearson/PVSystems#6]
Hi everyone,
I am currently using the basic layout of example PVInverter1Phase along with mppt tracker .
How can I achieve AC output at 230 V instead of the same amplitude on DC side?

Thank you in advance.

**Comment by raulrpearson** [comment]
@AggelikiGk, sorry,  I haven't been keeping track of this repo's issues. Did you manage to solve your problem?
