### ISSUE TITLE
if construct in PV cell wrong

### ISSUE THREAD

**Issue by max-privato** [raulrpearson/PVSystems#8]
Consider example model PVArrayVerification.
When run, the current goes to zero near the end of the simulation. This means that the model does not simulate negative currents when voltage overcomes OCV. 
However, if I change temperature Tn, for instance from 298.15 to 298.15+10, the current the cell delivers goes negative: this is because the internal if: is:
`  if v < 0 then
    i = v/((Rs + Rp)/Np); 
  elseif v > Vocn then
    i = 0;
  else
    i = -Np*(Ipv - Id - Ir);
  end if;
`
i.e., it switches to i=0 when V>Vocn, with, for temperatures different from the nominal, is different from the actual open-circuit voltage.

**Comment by raulrpearson** [comment]
As mentioned on the other issue, it's a long time since I did this. Is this still a problem for you? If it is, I might be able to carve out some time to look into it.

**Comment by max-privato** [comment]
Personally I don't need this ticket to be solved anymore.
So, it just your decision. 
Thank you for your consideration of my report.
